#!/usr/bin/env bash
# configure a new server and add a header X-Served-By

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx Http'
sudo sed -i "28i\add_header X-Served-By '$HOSTNAME';" /etc/nginx/nginx.conf
sudo service nginx restart
