#!/usr/bin/env bash
# Install your load balancer
sudo apt-get -y update
sudo apt-get -y install haproxy
sudo chown  $USER:$USER /etc/haproxy/haproxy.cfg

echo "
frontend maxton4life
    bind *:80
    mode http
    default_backend app
backend app
    balance roundrobin
    server 27205-web-01 44.200.111.35:80 check
    server 27205-web-02 3.238.84.38:80 check" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
