#!/usr/bin/env bash
# prints Best School ten times using while loop
# and print Hi on the nineth iteration

i=1
while [ $i -lt 11 ]
do
	echo "Best School"
	if [ $i == 9 ]
	then
		echo "Hi"
	fi
	(( i++ ))
done
