#!/usr/bin/env bash
# print bad luck for the 4th loop iteration
# print good luck for the 8th loop iteration
# print Best School for the other iteration using while

i=1
while [ $i -lt 11 ]
do
	if [ $i == 4 ]
	then
		echo "bad luck"
	elif [ $i == 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	(( i++ ))
done
