#!/usr/bin/env bash
# print bad luck from china at  4th iteration after printing 4
# print bad luck from japan at  9th iteration after printing 9 
# print bad luck from italy at  17th iteration after printing 17

i=1
while [ $i -le 20 ]
do
	case $i in
		4)
			echo "$i"
			echo "bad luck from China"
			;;
		9)
			echo "$i"
			echo "bad luck from Japan"
			;;
		17)
			echo "$i"
			echo "bad luck from Italy"
			;;
		*)
			echo "$i"
			;;
	esac
	(( i++ ))
done
